### ISSUE TITLE
關於backend的問題

### ISSUE THREAD

**Issue by ronald-chun** [jyun1desu/Hotel-Reservation#1]
你好
因為找不到你啲聯絡方法
所以只好在這裡留言
請問這個系統的backend 是用什麼language 去開發？
因為我正在找一些類似的backend

**Comment by jyun1desu** [comment]
hi ronald,
這個是六角學院辦的 F2E 活動，後端 API 是他們開的，可能要去問他們
這邊是網址：https://challenge.thef2e.com/news/17
希望能幫助到你
